name: dbt PR Validation

on: 
  pull_request:
    branches: 
      - main

jobs:
  dbt-validate_pr:
    name: dbt PR Validation
    runs-on: ubuntu-latest

    env:
      DBT_API_KEY:             ${{ secrets.DBT_API_KEY }}
      DBT_URL:                 https://c2.us1.dbt.com # no trailing backslash. Change this for single tenant deployments to your actual base url
      DBT_JOB_CAUSE:           'Github Actions PR Job' # provide a descriptive job cause here for easy debugging down the road
      DBT_ACCOUNT_ID:          70437463654684
      DBT_PROJECT_ID:          70437463655816
      DBT_PR_JOB_ID:           70437463676816
      DBT_JOB_SCHEMA_OVERRIDE: PR_GITHUB_ACTIONS_${{github.event.pull_request.number}}
      DBT_JOB_BRANCH:          ${{github.head_ref}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Trigger dbt job
      run: |
        python -u ./python/run_and_monitor_dbt_cloud_job.py
